### ISSUE TITLE
Transformation error (parse is not a function)

### ISSUE THREAD

**Issue by vst** [kaliber5/ember-bootstrap-codemods#5]
I am receiving `Transformation error (parse is not a function)` error.

Call:

```
npx ember-bootstrap-codemods deprecated-attribute-arguments app/**/*.hbs
```

Result:

```
npx: installed 461 in 13.561s
Processing 404 files...
Spawning 7 workers...
Sending 50 files to free worker...
Sending 50 files to free worker...
[... truncated ...]
 ERR app/myroute/template.hbs Transformation error (parse is not a function)
TypeError: parse is not a function
    at module.exports (/home/user/.npm/_npx/16806/lib/node_modules/ember-bootstrap-codemods/transforms/deprecated-attribute-arguments/index.js:165:15)
[... truncated ...]
All done.
Results:
404 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 0.973seconds
```

Using:

```
Ember           : 3.19.0
Ember Data      : 3.19.0
Ember Bootstrap : 3.1.4
Node            : 12.16.1
```

Do you think that I am missing something?

**Comment by bahdvp** [comment]
Same issue on ember 3.18 and node 12.18.2. I imagine it might be resolved by updating node to 14.x but not quite ready to do that.

**Comment by simonihmig** [comment]
Thanks for reporting! It's not related to node, rather it was using a fork of `codemod-cli` while the upstream PR was in review (merged now), which has been modified meanwhile. I need to fix the dependencies here, sorry for the trouble! 😔

**Comment by vst** [comment]
No problem and thanks for all your efforts!
